server:
  port: 9200

spring:
  datasource:
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8;
    url: jdbc:mysql://localhost/calendar?useSSL=false&createDatabaseIfNotExist=true
    username: calendar
    password: calendar
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  security:
    user:
      name: admin
      password: admin
