server:
  port: 9200

spring:
  datasource:
    url: jdbc:mysql://localhost/calendar?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: admin
      password: admin
